name: Deploy Website
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Jekyll Action
        uses: helaili/jekyll-action@master
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
